// <auto-generated />
using System;
using CustomerAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerAPI.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20240103235708_updatedStaticData")]
    partial class updatedStaticData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4883),
                            Email = "John123@email.com",
                            FirstName = "John",
                            LastName = "Doe",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4968)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4972),
                            Email = "Jane123@email.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4974)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4977),
                            Email = "Smith123@email.com",
                            FirstName = "Smith",
                            LastName = "Dow",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4979)
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4981),
                            Email = "Michael123@email.com",
                            FirstName = "Michael",
                            LastName = "John",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4983)
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4985),
                            Email = "Brian123@email.com",
                            FirstName = "Brian",
                            LastName = "Brian",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4986)
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4988),
                            Email = "Donald123@email.com",
                            FirstName = "Donald",
                            LastName = "Donald",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4990)
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4992),
                            Email = "Jesse123@email.com",
                            FirstName = "Jesse",
                            LastName = "Jesse",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4994)
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4996),
                            Email = "Juan123@email.com",
                            FirstName = "Juan",
                            LastName = "Juan",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4997)
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(4999),
                            Email = "Brandon123@email.com",
                            FirstName = "Brandon",
                            LastName = "Brandon",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5001)
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5003),
                            Email = "Bradford123@email.com",
                            FirstName = "Bradford",
                            LastName = "Bradford",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5005)
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5007),
                            Email = "Riley123@email.com",
                            FirstName = "Riley",
                            LastName = "Riley",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5009)
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5011),
                            Email = "Catarino123@email.com",
                            FirstName = "Catarino",
                            LastName = "Catarino",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5012)
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5015),
                            Email = "William123@email.com",
                            FirstName = "William",
                            LastName = "William",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5016)
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5018),
                            Email = "Michael123@email.com",
                            FirstName = "Michael",
                            LastName = "Michael",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5020)
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5022),
                            Email = "James123@email.com",
                            FirstName = "James",
                            LastName = "Smith",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5024)
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5026),
                            Email = "Irving123@email.com",
                            FirstName = "Irving",
                            LastName = "Irving",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5027)
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5029),
                            Email = "Donald123@email.com",
                            FirstName = "Donald",
                            LastName = "Donald",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5031)
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5033),
                            Email = "Ryan123@email.com",
                            FirstName = "Ryan",
                            LastName = "Ryan",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5034)
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5036),
                            Email = "Renzy123@email.com",
                            FirstName = "Renzy",
                            LastName = "Renzy",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5038)
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5040),
                            Email = "Arash123@email.com",
                            FirstName = "Arash",
                            LastName = "Arash",
                            UpdatedOn = new DateTime(2024, 1, 3, 17, 57, 8, 12, DateTimeKind.Local).AddTicks(5041)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
